export enum ModalidadeFreteNfeEnum {
  FRETE_POR_CONTA_DO_REMETENTE_CIF = 0,
  FRETE_POR_CONTA_DO_DESTINATARIO_FOB = 1,
  FRETE_POR_CONTA_DE_TERCEIROS = 2,
  TRANSPORTE_PROPRIO_POR_CONTA_DO_REMETENTE = 3,
  TRANSPORTE_PROPRIO_POR_CONTA_DO_DESTINATARIO = 4,
  SEM_OCORRENCIA_DE_TRANSPORTE = 9,
}
