import { CsosnCfEnum } from "../enums/csosn-cf.enum";
import { CstCfEnum } from "../enums/cst-cf.enum";
import { ModalidadeDeterminacaoBcIcmsStEnum } from "../enums/modalidade-de-determinacao-da-bc-icms-st.enum";
import { ModalidadeDeterminacaoBcEnum } from "../enums/modalidade-de-determinacao-da-bc.enum";
import { MotivoDesoneracaoIcmsStEnum } from "../enums/motivo-da-desoneracao-do-icms-st.enum";
import { UnidadeFederativaEnum } from "../enums/nfe-nfce.enum";
import { OrigemMercadoriaEnum } from "../enums/origem-da-mercadoria.enum";

export interface IcmsModel {
  csosn: CsosnCfEnum;
  orig: OrigemMercadoriaEnum;
  cst: string;
  modBc: ModalidadeDeterminacaoBcEnum;
  pRedBc: number;
  vBc: number;
  pIcms: number;
  vIcms: number;
  modBcSt: ModalidadeDeterminacaoBcIcmsStEnum;
  pMvast: number;
  pRedBcSt: number;
  vBcSt: number;
  pIcmsSt: number;
  vIcmsSt: number;
  ufSt: UnidadeFederativaEnum;
  pBcOp: number;
  vBcStRet: number;
  vIcmsStRet: number;
  motDesIcms: MotivoDesoneracaoIcmsStEnum;
  pCredSn: number;
  vCredIcmsSn: number;
  vBcStDest: number;
  vIcmsStDest: number;
  vIcmsDeson: number;
  vIcmsOp: number;
  pDif: number;
  vIcmsDif: number;
  pSt: number;
  vBcFcp: number;
  pFcp: number;
  vFcp: number;
  vBcFcpSt: number;
  pFcpSt: number;
  vFcpSt: number;
  vBcFcpStRet: number;
  pFcpStRet: number;
  vFcpStRet: number;
  pRedBcEfet: number;
  vBcEfet: number;
  pIcmsEfet: number;
  vIcmsEfet: number;
  vIcmsSubstituto: number;
  vIcmsStDeson: number;
  motDesIcmsSt: number;
  pFcpDif: number;
  vFcpDif: number;
  pFcpEfet: number;
}
