import {
  CodigoModeloDocumentoFiscalEnum,
  CodigoRegimeTributarioEnum,
  CodigoUnidadeFederativaEnum,
  FinalidadeEmissaoNfeEnum,
  IdentificacaoAmbienteEnum,
  IdentificacaoNfeEnum,
  IdentificadorLocalDestinoOperacaoEnum,
  IndicadorFormaPagamentoEnum,
  IndicadorIeDestinatarioEnum,
  IndicadorPresencaEnum,
  IndicadorSeValorItemEntraTotalNfeEnum,
  NaturezaOperacaoEnum,
  IndicadorOperacaoConsumidorFinalEnum,
  ProcessoEmissaoNfeEnum,
  TipoEmissaoNfeEnum,
  TipoOperacaoEnum,
  UnidadeFederativaEnum,
} from "./enums/nfe-nfce.enum";

import {
  CodigoModeloDocumentoFiscalModel,
  CodigoRegimeTributarioModel,
  CodigoUnidadeFederativaModel,
  FinalidadeEmissaoNfeModel,
  IdentificacaoAmbienteModel,
  IdentificacaoNfeModel,
  IdentificadorLocalDestinoOperacaoModel,
  IndicadorFormaPagamentoModel,
  IndicadorIeDestinatarioModel,
  IndicadorPresencaModel,
  IndicadorSeValorItemEntraTotalNfeModel,
  NaturezaOperacaoModel,
  IndicadorOperacaoConsumidorFinalModel,
  ProcessoEmissaoNfeModel,
  TipoEmissaoNfeModel,
  TipoOperacaoModel,
  UnidadeFederativaModel,
} from "./models/nfe-nfce.model";

import {
  codigoModeloDocumentoFiscalList,
  codigoRegimeTributarioList,
  codigoUnidadeFederativaList,
  finalidadeEmissaoNfeList,
  identificacaoAmbienteList,
  identificacaoNfeList,
  identificadorLocalDestinoOperacaoList,
  indicadorFormaPagamentoList,
  indicadorIeDestinatarioList,
  indicadorPresencaList,
  indicadorSeValorItemEntraTotalNfeList,
  naturezaOperacaoList,
  indicadorOperacaoConsumidorFinalList,
  processoEmissaoNfeList,
  tipoEmissaoNfeList,
  tipoOperacaoList,
  unidadeFederativaList,
} from "./lists/nfe-nfce.list";

export {
  CodigoModeloDocumentoFiscalEnum,
  CodigoRegimeTributarioEnum,
  CodigoUnidadeFederativaEnum,
  FinalidadeEmissaoNfeEnum,
  IdentificacaoAmbienteEnum,
  IdentificacaoNfeEnum,
  IdentificadorLocalDestinoOperacaoEnum,
  IndicadorFormaPagamentoEnum,
  IndicadorIeDestinatarioEnum,
  IndicadorPresencaEnum,
  IndicadorSeValorItemEntraTotalNfeEnum,
  NaturezaOperacaoEnum,
  IndicadorOperacaoConsumidorFinalEnum,
  ProcessoEmissaoNfeEnum,
  TipoEmissaoNfeEnum,
  TipoOperacaoEnum,
  UnidadeFederativaEnum,

  // MODELS
  CodigoModeloDocumentoFiscalModel,
  CodigoRegimeTributarioModel,
  CodigoUnidadeFederativaModel,
  FinalidadeEmissaoNfeModel,
  IdentificacaoAmbienteModel,
  IdentificacaoNfeModel,
  IdentificadorLocalDestinoOperacaoModel,
  IndicadorFormaPagamentoModel,
  IndicadorIeDestinatarioModel,
  IndicadorPresencaModel,
  IndicadorSeValorItemEntraTotalNfeModel,
  NaturezaOperacaoModel,
  IndicadorOperacaoConsumidorFinalModel,
  ProcessoEmissaoNfeModel,
  TipoEmissaoNfeModel,
  TipoOperacaoModel,
  UnidadeFederativaModel,

  // LISTS
  codigoModeloDocumentoFiscalList,
  codigoRegimeTributarioList,
  codigoUnidadeFederativaList,
  finalidadeEmissaoNfeList,
  identificacaoAmbienteList,
  identificacaoNfeList,
  identificadorLocalDestinoOperacaoList,
  indicadorFormaPagamentoList,
  indicadorIeDestinatarioList,
  indicadorPresencaList,
  indicadorSeValorItemEntraTotalNfeList,
  naturezaOperacaoList,
  indicadorOperacaoConsumidorFinalList,
  processoEmissaoNfeList,
  tipoEmissaoNfeList,
  tipoOperacaoList,
  unidadeFederativaList,
};
